# Generated by Django 3.2.9 on 2021-11-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_streamplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-11-11 18:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='moviePlatform',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='movie.streamplatform'),
        ),
    ]
