# Generated by Django 3.2.9 on 2021-11-15 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_auto_20211113_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_comment',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
